{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "import tensorflow as tf\n",
    "sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<tensorflow.python.client.session.Session object at 0x7fcaa0495080>\n"
     ]
    }
   ],
   "source": [
    "print(sess)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "ename": "InvalidArgumentError",
     "evalue": "Cannot assign a device for operation MatMul: node MatMul (defined at <ipython-input-3-366263745427>:4) was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0 ]. Make sure the device specification refers to a valid device. The requested device appears to be a GPU, but CUDA is not enabled.\n\t [[node MatMul (defined at <ipython-input-3-366263745427>:4) ]]\n\nCaused by op 'MatMul', defined at:\n  File \"/home/slingblade/anaconda3/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n  File \"/home/slingblade/anaconda3/lib/python3.7/runpy.py\", line 85, in _run_code\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/ipykernel/kernelapp.py\", line 505, in start\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tornado/platform/asyncio.py\", line 132, in start\n  File \"/home/slingblade/anaconda3/lib/python3.7/asyncio/base_events.py\", line 528, in run_forever\n  File \"/home/slingblade/anaconda3/lib/python3.7/asyncio/base_events.py\", line 1764, in _run_once\n  File \"/home/slingblade/anaconda3/lib/python3.7/asyncio/events.py\", line 88, in _run\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py\", line 758, in _run_callback\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tornado/stack_context.py\", line 300, in null_wrapper\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tornado/gen.py\", line 1233, in inner\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tornado/gen.py\", line 1147, in run\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 357, in process_one\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tornado/gen.py\", line 326, in wrapper\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 267, in dispatch_shell\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tornado/gen.py\", line 326, in wrapper\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 534, in execute_request\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tornado/gen.py\", line 326, in wrapper\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/ipykernel/ipkernel.py\", line 294, in do_execute\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2819, in run_cell\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2845, in _run_cell\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/IPython/core/async_helpers.py\", line 67, in _pseudo_sync_runner\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3020, in run_cell_async\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3185, in run_ast_nodes\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3267, in run_code\n  File \"<ipython-input-3-366263745427>\", line 4, in <module>\n    c = tf.matmul(a, b)\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py\", line 2455, in matmul\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/gen_math_ops.py\", line 5333, in mat_mul\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py\", line 788, in _apply_op_helper\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py\", line 507, in new_func\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py\", line 3300, in create_op\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py\", line 1801, in __init__\n\nInvalidArgumentError (see above for traceback): Cannot assign a device for operation MatMul: node MatMul (defined at <ipython-input-3-366263745427>:4) was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0 ]. Make sure the device specification refers to a valid device. The requested device appears to be a GPU, but CUDA is not enabled.\n\t [[node MatMul (defined at <ipython-input-3-366263745427>:4) ]]\n",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mInvalidArgumentError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[0;32m~/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py\u001b[0m in \u001b[0;36m_do_call\u001b[0;34m(self, fn, *args)\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py\u001b[0m in \u001b[0;36m_run_fn\u001b[0;34m(feed_dict, fetch_list, target_list, options, run_metadata)\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py\u001b[0m in \u001b[0;36m_extend_graph\u001b[0;34m(self)\u001b[0m\n",
      "\u001b[0;31mInvalidArgumentError\u001b[0m: Cannot assign a device for operation MatMul: {{node MatMul}}was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0 ]. Make sure the device specification refers to a valid device. The requested device appears to be a GPU, but CUDA is not enabled.\n\t [[{{node MatMul}}]]",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mInvalidArgumentError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-9-366263745427>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      6\u001b[0m \u001b[0;32mwith\u001b[0m \u001b[0mtf\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mSession\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0msess\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 7\u001b[0;31m     \u001b[0mprint\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0msess\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrun\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mc\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py\u001b[0m in \u001b[0;36mrun\u001b[0;34m(self, fetches, feed_dict, options, run_metadata)\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py\u001b[0m in \u001b[0;36m_run\u001b[0;34m(self, handle, fetches, feed_dict, options, run_metadata)\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py\u001b[0m in \u001b[0;36m_do_run\u001b[0;34m(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py\u001b[0m in \u001b[0;36m_do_call\u001b[0;34m(self, fn, *args)\u001b[0m\n",
      "\u001b[0;31mInvalidArgumentError\u001b[0m: Cannot assign a device for operation MatMul: node MatMul (defined at <ipython-input-3-366263745427>:4) was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0 ]. Make sure the device specification refers to a valid device. The requested device appears to be a GPU, but CUDA is not enabled.\n\t [[node MatMul (defined at <ipython-input-3-366263745427>:4) ]]\n\nCaused by op 'MatMul', defined at:\n  File \"/home/slingblade/anaconda3/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n  File \"/home/slingblade/anaconda3/lib/python3.7/runpy.py\", line 85, in _run_code\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/ipykernel/kernelapp.py\", line 505, in start\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tornado/platform/asyncio.py\", line 132, in start\n  File \"/home/slingblade/anaconda3/lib/python3.7/asyncio/base_events.py\", line 528, in run_forever\n  File \"/home/slingblade/anaconda3/lib/python3.7/asyncio/base_events.py\", line 1764, in _run_once\n  File \"/home/slingblade/anaconda3/lib/python3.7/asyncio/events.py\", line 88, in _run\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py\", line 758, in _run_callback\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tornado/stack_context.py\", line 300, in null_wrapper\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tornado/gen.py\", line 1233, in inner\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tornado/gen.py\", line 1147, in run\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 357, in process_one\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tornado/gen.py\", line 326, in wrapper\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 267, in dispatch_shell\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tornado/gen.py\", line 326, in wrapper\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 534, in execute_request\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tornado/gen.py\", line 326, in wrapper\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/ipykernel/ipkernel.py\", line 294, in do_execute\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2819, in run_cell\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2845, in _run_cell\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/IPython/core/async_helpers.py\", line 67, in _pseudo_sync_runner\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3020, in run_cell_async\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3185, in run_ast_nodes\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3267, in run_code\n  File \"<ipython-input-3-366263745427>\", line 4, in <module>\n    c = tf.matmul(a, b)\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py\", line 2455, in matmul\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/gen_math_ops.py\", line 5333, in mat_mul\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py\", line 788, in _apply_op_helper\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py\", line 507, in new_func\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py\", line 3300, in create_op\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py\", line 1801, in __init__\n\nInvalidArgumentError (see above for traceback): Cannot assign a device for operation MatMul: node MatMul (defined at <ipython-input-3-366263745427>:4) was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0 ]. Make sure the device specification refers to a valid device. The requested device appears to be a GPU, but CUDA is not enabled.\n\t [[node MatMul (defined at <ipython-input-3-366263745427>:4) ]]\n"
     ]
    }
   ],
   "source": [
    "with tf.device('/gpu:0'):\n",
    "    a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')\n",
    "    b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')\n",
    "    c = tf.matmul(a, b)\n",
    "\n",
    "with tf.Session() as sess:\n",
    "    print (sess.run(c))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "ename": "InvalidArgumentError",
     "evalue": "Cannot assign a device for operation MatMul: node MatMul (defined at <ipython-input-3-366263745427>:4) was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0 ]. Make sure the device specification refers to a valid device. The requested device appears to be a GPU, but CUDA is not enabled.\n\t [[node MatMul (defined at <ipython-input-3-366263745427>:4) ]]\n\nCaused by op 'MatMul', defined at:\n  File \"/home/slingblade/anaconda3/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n  File \"/home/slingblade/anaconda3/lib/python3.7/runpy.py\", line 85, in _run_code\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/ipykernel/kernelapp.py\", line 505, in start\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tornado/platform/asyncio.py\", line 132, in start\n  File \"/home/slingblade/anaconda3/lib/python3.7/asyncio/base_events.py\", line 528, in run_forever\n  File \"/home/slingblade/anaconda3/lib/python3.7/asyncio/base_events.py\", line 1764, in _run_once\n  File \"/home/slingblade/anaconda3/lib/python3.7/asyncio/events.py\", line 88, in _run\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py\", line 758, in _run_callback\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tornado/stack_context.py\", line 300, in null_wrapper\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tornado/gen.py\", line 1233, in inner\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tornado/gen.py\", line 1147, in run\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 357, in process_one\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tornado/gen.py\", line 326, in wrapper\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 267, in dispatch_shell\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tornado/gen.py\", line 326, in wrapper\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 534, in execute_request\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tornado/gen.py\", line 326, in wrapper\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/ipykernel/ipkernel.py\", line 294, in do_execute\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2819, in run_cell\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2845, in _run_cell\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/IPython/core/async_helpers.py\", line 67, in _pseudo_sync_runner\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3020, in run_cell_async\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3185, in run_ast_nodes\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3267, in run_code\n  File \"<ipython-input-3-366263745427>\", line 4, in <module>\n    c = tf.matmul(a, b)\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py\", line 2455, in matmul\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/gen_math_ops.py\", line 5333, in mat_mul\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py\", line 788, in _apply_op_helper\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py\", line 507, in new_func\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py\", line 3300, in create_op\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py\", line 1801, in __init__\n\nInvalidArgumentError (see above for traceback): Cannot assign a device for operation MatMul: node MatMul (defined at <ipython-input-3-366263745427>:4) was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0 ]. Make sure the device specification refers to a valid device. The requested device appears to be a GPU, but CUDA is not enabled.\n\t [[node MatMul (defined at <ipython-input-3-366263745427>:4) ]]\n",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mInvalidArgumentError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[0;32m~/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py\u001b[0m in \u001b[0;36m_do_call\u001b[0;34m(self, fn, *args)\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py\u001b[0m in \u001b[0;36m_run_fn\u001b[0;34m(feed_dict, fetch_list, target_list, options, run_metadata)\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py\u001b[0m in \u001b[0;36m_extend_graph\u001b[0;34m(self)\u001b[0m\n",
      "\u001b[0;31mInvalidArgumentError\u001b[0m: Cannot assign a device for operation MatMul: {{node MatMul}}was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0 ]. Make sure the device specification refers to a valid device. The requested device appears to be a GPU, but CUDA is not enabled.\n\t [[{{node MatMul}}]]",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mInvalidArgumentError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-10-2b49938bcf61>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      9\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     10\u001b[0m \u001b[0;32mwith\u001b[0m \u001b[0mtf\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mSession\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0msess\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 11\u001b[0;31m     \u001b[0mprint\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0msess\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrun\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mc\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py\u001b[0m in \u001b[0;36mrun\u001b[0;34m(self, fetches, feed_dict, options, run_metadata)\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py\u001b[0m in \u001b[0;36m_run\u001b[0;34m(self, handle, fetches, feed_dict, options, run_metadata)\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py\u001b[0m in \u001b[0;36m_do_run\u001b[0;34m(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py\u001b[0m in \u001b[0;36m_do_call\u001b[0;34m(self, fn, *args)\u001b[0m\n",
      "\u001b[0;31mInvalidArgumentError\u001b[0m: Cannot assign a device for operation MatMul: node MatMul (defined at <ipython-input-3-366263745427>:4) was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0 ]. Make sure the device specification refers to a valid device. The requested device appears to be a GPU, but CUDA is not enabled.\n\t [[node MatMul (defined at <ipython-input-3-366263745427>:4) ]]\n\nCaused by op 'MatMul', defined at:\n  File \"/home/slingblade/anaconda3/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n  File \"/home/slingblade/anaconda3/lib/python3.7/runpy.py\", line 85, in _run_code\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/ipykernel/kernelapp.py\", line 505, in start\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tornado/platform/asyncio.py\", line 132, in start\n  File \"/home/slingblade/anaconda3/lib/python3.7/asyncio/base_events.py\", line 528, in run_forever\n  File \"/home/slingblade/anaconda3/lib/python3.7/asyncio/base_events.py\", line 1764, in _run_once\n  File \"/home/slingblade/anaconda3/lib/python3.7/asyncio/events.py\", line 88, in _run\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py\", line 758, in _run_callback\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tornado/stack_context.py\", line 300, in null_wrapper\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tornado/gen.py\", line 1233, in inner\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tornado/gen.py\", line 1147, in run\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 357, in process_one\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tornado/gen.py\", line 326, in wrapper\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 267, in dispatch_shell\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tornado/gen.py\", line 326, in wrapper\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 534, in execute_request\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tornado/gen.py\", line 326, in wrapper\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/ipykernel/ipkernel.py\", line 294, in do_execute\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2819, in run_cell\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2845, in _run_cell\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/IPython/core/async_helpers.py\", line 67, in _pseudo_sync_runner\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3020, in run_cell_async\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3185, in run_ast_nodes\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3267, in run_code\n  File \"<ipython-input-3-366263745427>\", line 4, in <module>\n    c = tf.matmul(a, b)\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py\", line 2455, in matmul\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/gen_math_ops.py\", line 5333, in mat_mul\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py\", line 788, in _apply_op_helper\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py\", line 507, in new_func\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py\", line 3300, in create_op\n  File \"/home/slingblade/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py\", line 1801, in __init__\n\nInvalidArgumentError (see above for traceback): Cannot assign a device for operation MatMul: node MatMul (defined at <ipython-input-3-366263745427>:4) was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0 ]. Make sure the device specification refers to a valid device. The requested device appears to be a GPU, but CUDA is not enabled.\n\t [[node MatMul (defined at <ipython-input-3-366263745427>:4) ]]\n"
     ]
    }
   ],
   "source": [
    "\n",
    "\n",
    "sess = tf.Session(config=tf.ConfigProto( allow_soft_placement=True, log_device_placement=True))\n",
    "\n",
    "with tf.device('/gpu:0'):\n",
    "    a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')\n",
    "    b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')\n",
    "    c = tf.matmul(a, b)\n",
    "\n",
    "with tf.Session() as sess:\n",
    "    print (sess.run(c))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
